#!/bin/bash

# ==============================================================================
#  脚本名称：armbian-sync
#  脚本功能：同步 Armbian-Actions 仓库中的 /patch/sbin 脚本到 /usr/sbin
# ==============================================================================

BASE_URL="https://raw.githubusercontent.com/Zane-E/Armbian-Actions/main/patch/sbin"
API_URL="https://api.github.com/repos/Zane-E/Armbian-Actions/contents/patch/sbin"
TARGET_DIR="/usr/sbin"

STEPS="[\033[95m 步骤 \033[0m]"
INFO="[\033[94m 信息 \033[0m]"
SUCCESS="[\033[92m 成功 \033[0m]"
ERROR="[\033[91m 错误 \033[0m]"

error() {
    echo -e "${ERROR} ${1}"
    exit 1
}

create_temp_dir() {
    TEMP_DIR=$(mktemp -d) || error "创建临时目录失败！"
    trap 'rm -rf "${TEMP_DIR}"' EXIT
}

load_system_info() {
    [[ -f /etc/os-release ]] || error "未找到 /etc/os-release 文件！"
    # shellcheck disable=SC1091
    source /etc/os-release

    ARCH=$(uname -m)
    SCRIPT_NAME=$(basename "${0}")
}

get_remote_scripts() {
    local filter

    echo -e "${STEPS} 正在获取文件列表..."

    filter='.[] | select(.name != $SCRIPT_NAME'
    if [[ ! "${VERSION_CODENAME}" =~ ^(bookworm|trixie)$ || ! "${ARCH}" =~ ^(aarch64|arm64)$ ]]; then
        filter+=' and .name != "install-pve"'
    fi

    FILES=$(curl -fsSL --retry 3 --retry-delay 1 --max-time 5 "${API_URL}" 2>/dev/null |
        jq -r --arg SCRIPT_NAME "${SCRIPT_NAME}" "${filter}) | .name") || error "获取文件列表失败！"

    [[ -n "${FILES}" ]] || error "文件列表为空！"

    echo -e "${SUCCESS} 获取文件列表成功！"
    for script in ${FILES}; do
        echo -e "${INFO} 文件名：[\033[92m ${script} \033[0m]"
    done
}

ensure_target_dir() {
    if [[ ! -d "${TARGET_DIR}" ]]; then
        echo -e "${ERROR} 目标目录 [\033[92m ${TARGET_DIR} \033[0m] 不存在！正在创建..."
        mkdir -p "${TARGET_DIR}" || error "创建目标目录失败！"
    fi
}

sync_scripts() {
    local script
    local script_url

    for script in ${FILES}; do
        script_url="${BASE_URL}/${script}"
        echo -e "${STEPS} 正在同步文件：[\033[92m ${script} \033[0m]"

        curl -fsSL --retry 3 --retry-delay 1 --max-time 5 -o "${TEMP_DIR}/${script}" "${script_url}" >/dev/null 2>&1 ||
            error "下载失败：[\033[92m ${script} \033[0m]"
        chmod +x "${TEMP_DIR}/${script}" || error "设置权限失败：[\033[92m ${script} \033[0m]"
        mv -f "${TEMP_DIR}/${script}" "${TARGET_DIR}/" || error "移动失败：[\033[92m ${script} \033[0m]"
    done

    echo -e "${SUCCESS} 文件同步完成！"
}

main() {
    create_temp_dir
    load_system_info
    get_remote_scripts
    ensure_target_dir
    sync_scripts
}

main "$@"
